server:
  port: 8010
mybatis:
  mapper-locations: classpath:mapping/*.xml

# 配置数据源
spring:
  datasource:
    name: dianpingdb
    url: jdbc:mysql://127.0.0.1:3306/dianpingdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    # 配置druid做datasource连接池管理
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  # 如果所有的controller都没有命中，使用默认的系统静态资源处理器处理
  resources:
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
    #接入前端静态资源页面
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html

admin:
  email: 625592378@qq.com
  encryptPassword: 4QrcOUm6Wau+VuBX8g+IPg==

