package com.afei.dianping.dal;

import com.afei.dianping.model.ShopModel;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface ShopModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jul 08 21:12:25 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jul 08 21:12:25 CST 2020
     */
    int insert(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jul 08 21:12:25 CST 2020
     */
    int insertSelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jul 08 21:12:25 CST 2020
     */
    ShopModel selectByPrimaryKey(Integer id);

    List<ShopModel> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jul 08 21:12:25 CST 2020
     */
    int updateByPrimaryKeySelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Wed Jul 08 21:12:25 CST 2020
     */
    int updateByPrimaryKey(ShopModel record);

    Integer countAllShop();

    List<ShopModel> recommend(@Param("longitude") BigDecimal longitude,@Param("latitude") BigDecimal latitude);
}